#! /bin/sh 
# -*- Mode:Shell-script -*-
set -e
target=Fan.byte
echo "cold start..."
make cleancold
ocamlbuild cold/$target

echo "cold start finished.. now bootstrapping to verify it could reach a fix point"
test -d _build/boot || mkdir _build/boot
test -f _build/boot/$target && mv _build/boot/$target _build/boot/$target.old
cp _build/cold/$target _build/boot/
test -e _build/boot/fan && rm _build/boot/fan

pushd . && cd _build/boot/ && ln -s $target fan && popd

./hb $target
