#! /bin/sh 
# -*- Mode:Shell-script -*-
target=$1
set -e
test _build/boot || mkdir _build/boot
test _build/boot/$target && mv _build/boot/$target _build/boot/$target.old
cp _build/src/$target _build/boot/
rm -f _build/boot/fan
ln -s $target _build/boot/fan