#! /bin/sh 
# -*- Mode:Shell-script -*-
set -e
dest=${1:-cold}
echo "snapshoping to $dest"

make cleantmp
ocamlbuild -I src $(find src | grep -v .# |  grep '\.\(ml\|mll\|mli\|mlpack\)$' | perl -pe 's|.*?/|tmp/|')
# needs copy mll mlpack as well

rm -rf $dest # do the cleaning, in case some files are discarded 
# mkdir cold

cp -rf _build/tmp/ $dest

echo "snapshop finished"
