#! /bin/sh 
# -*- Mode:Shell-script -*-

# e.g, snapshot tmp
# default to cold


set -e
dest=${1:-cold}
echo "snapshoping to $dest"
files=$(find src | grep -v .# |  grep '\.\(ml\|mll\|mli\|mlpack\|mlp\|mllib\)$' | perl -pe 's|.*?/|tmp/|')
make cleantmp
ocamlbuild -I src $files
# needs copy mll mlpack as well

rm -rf $dest # do the cleaning, in case some files are discarded 
# mkdir cold

cp -rf _build/tmp/ $dest

echo "snapshop finished"
