#+OPTIONS: toc:nil html-postamble:nil html-preamble:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="stylesheets/styles.css" />
#+TITLE: Getting started
#+OPTIONS: ^:{}
#+OPTIONS: toc:nil
#+TOC:headines 2



The following post assumes the reader is already familiar with OCaml.
If you are not familiar with OCaml, we sugget you to get started here:
http://ocaml.org/
for you to learn.

* Installation
  see [[file:install.org][Installation]]


* What language does Fan speak?
  See [[file:syntax.org][syntax]]

* A high-level overview of Fan's architecture.
  There is a paper, which gives a high-level priciple about how Fan
  works, available here [[file:pdf/metaprogramming_for_ocaml.pdf]]

* Compiing with Fan
  See [[file:compilation.org][compilation]]

* Fan for toplevel 
  See [[file:toplevel_support.org][Toplevel support]]

  
* Fan's quotation system
  see [[file:quotation_system.org][Fan's quasiquotation]]

* Fan's parsing scheme
  see [[file:parser.org][parser DDSL]]
* Fan's lexing scheme 
  see [[file:lexer.org][lexer DDSL]]

* Writing plugins for Fan
  see [[file:plugins.org][Plugins]]

  


   
